### ISSUE TITLE
objekte mit adjustToTerrainHeight sichtbarkeitsprob...

### ISSUE THREAD

**Issue by thoralf2002** [mor2000/UniversalProcessKit_FS15#11]
Hallo, ich schon wieder ;) , mit oben genannten boolean versehene objekte sind beim plazieren nicht sichtbar :( ... nur beim plazieren, sobald plaziert stehen sie da ... dies sollte unbedingt nochmal geprüft werden....

**Comment by mor2000** [comment]
hab ich gefixt, glaub ich
