### ISSUE TITLE
mover - mover für Grainstation Abkippstellen...

### ISSUE THREAD

**Issue by thoralf2002** [mor2000/UniversalProcessKit_FS15#30]
hallo, wenn möglich bitte für Grainstation haufen eine funktion haufen hoch beim kippen und absenken in einer gewissen zeit, also ein zeitfunktion hinzufügen - moveBackTime 
moveByTipping - oder so .... als kleine spielereit für die optik :) ... also ohne das das Fill verarbeitet wird...

**Comment by mor2000** [comment]
sorry, versteh ich gerade nicht. kannst du das beispiel noch mehr ausführen?

**Comment by thoralf2002** [comment]
ja kann ich, ich kippe zum beispiel raps in der Biofuelanlage ab. beim kippen soll sich ein Haufen bilden welcher nach 60 sekunden wieder verschwindet und das langsam - linear...

**Comment by mor2000** [comment]
Das kannst du doch mit nem processor machen:

- base (store="wheat", convertFillTypes="wheat pushwheat")
- processor (store="wheat", product="pushwheat", recipe="1 wheat", productsPerSecond="500")
-- mover
-- tiptrigger

**Comment by thoralf2002** [comment]
hallo, das verstehe ich jetzt nicht - store im processor? und in der base auch ein store? 
würde dann der raps erhalten bleiben für die produktion von fuel? - fragen über fragen :)
nach meinem bisherigen verständnis entsteht durch das convertFillTypes ja bereits pushwheat in der base, jetzt hast du einen processor mit einer ?store? - (bei ls13,hattest du mal geschrieben, dies wäre ein hack) und produzierst ebenfalls pushwheat? aus einem wheat -> kann es sein du meintest: store=pushrape , produkt=rape, recipe="1 pushrape", productsPerSecond="500" -> dies würde mir dann noch eventuell sinn machen - denn dann wäre rape wieder da und stände für den zweiten processor zur verfügung -> weiter dann dieser "schnellmover" als Kind und der tiptrigger ebenfalls als Kind des mover-processors, ... -> liege ich damit richtig?
Darunter dann der  zweite processor der fuel produziert ... richtig? ...

**Comment by mor2000** [comment]
Im UPK13 hat es nicht so ganz funktioniert, aber beim 15er habe ich "store" unter den Standard-UserAttributes gelistet, die man in jedem Modul verwenden kann.
Was das Beispiel macht: im tiptrigger kommt wheat an. Der fragt sich "kann ich wheat speichern?", nein, dann fragt er sein übergeordnetes Modul, hier der processor, "kannst du wheat speichern?". Das geht klar und im processor wird wheat gespeichert. Es wird nicht noch doppelt in der base gespeichert. Der processor wandelt es dann zu pushwheat um, dass er nicht speichern kann, aber die base (durch convertFillTypes), die es sofort zu wheat ändert.
Der mover reagiert auf den wheat Füllstand des processor, der nach dem Abkippen kleiner wird.

**Comment by thoralf2002** [comment]
OK, danke für diese Erläuterung :), jetzt wird mir so einiges klar. Ist zwar bischen kompliziert für mich zu händeln, aber wenn es funktioniert ist es i.O. :)
