### ISSUE TITLE
Animator?

### ISSUE THREAD

**Issue by jhomer** [mor2000/UniversalProcessKit_FS15#33]
Maybe I must be doing something wrong but I'm trying to make an object rotate while it's processing.
This is what the processor user attributes are:
![capture](https://cloud.githubusercontent.com/assets/7943994/5715826/ca63a25e-9aa5-11e4-8e77-85dedc4a75d8.JPG)
And in the group is the object I'm trying to get to rotate while it's processing.
My objective is for the "mixer" object to keep rotating while it's processing.
Also I was trying to get an audio clip to play while it's processing. (not sure if this is even possible)
![capture2](https://cloud.githubusercontent.com/assets/7943994/5715828/cffaa578-9aa5-11e4-9ac8-ed4ba10ac11d.JPG)

I apologize if this is not the place for questions but if you have any suggestions it would be appreciated.
Thanks!

**Comment by thoralf2002** [comment]
here is my solution for rotate with animator
```xml
<Attribute name="rotateTo" type="string" value="0 360 0"/>
      <Attribute name="rotationsPerSecond" type="string" value="0 0.2 0"/>
```
i hope this help you ... i have that not stay with children...

**Comment by mor2000** [comment]
Yeah, seems like rotationsPerSecond is what you want. These enable/disable-Attributes are set correctly. Do you have a space in the type-Attribute at " animator"? (I may add a trim function to prevent this)

**Comment by jhomer** [comment]
Thanks @thoralf2002 and @mor2000 for your responses!
I changed to rotationsPerSecond and I also did have a space in front of "animator".
Still did not work, then I looked at the i3d in notepad++ and I noticed a space in front of "type" for the animator as well. Fixed that and worked great!

The problem now is that the "mixer" turns the wrong direction:
one would think changing: <Attribute name="rotateTo" type="string" value="0 360 0"/>
to <Attribute name="rotateTo" type="string" value="0 -360 0"/> would change the turn direction but this does not seem to work. I even tried numbers like 45 and -45 but everything seems to have the same result. Everything I tried it always turns the same direction.
It's a good chance I'm doing something wrong AGAIN!
Any ideas?

Also can an audio clip be activated by the processor as well?
(to be played only while processing)
I've tried a few things with no success.

I thank you guys for your time and @mor2000 for the GREAT mod!

**Comment by jhomer** [comment]
Update: 
I did get the object in the "mover" to turn the opposite direction by creating a transform group, then rotate the transform 180 degrees. Then add the object to the group and rotate it back 180 degrees.

Nothing figured out yet for the audio clip activated by the processor yet.

**Comment by mor2000** [comment]
yeah, shut, I have a min(rotation/move, 0) function in the code which prevents negative values. will be fixed
