### ISSUE TITLE
filltypes created within the upk that are not registered in the map do not update properly on servers

### ISSUE THREAD

**Issue by dajnet** [mor2000/UniversalProcessKit_FS15#35]
I created a filltype called power. I used a processor to turn wood chips into power and also included a switcher to turn a light on when power was available. everything works fine in single and multiplayer but on server, the displaytrigger, switcher, processor do not update. If I register the filltype "power" within the map, then everything works but I am already maxed out on filltypes at 64

**Comment by mor2000** [comment]
thats good to know! I'll correct that

**Comment by mor2000** [comment]
fixed in V0.9.5

**Comment by dajnet** [comment]
excellent! Can't wait to get it!

**Comment by mor2000** [comment]
just posted it on twitter (has 2 callstacks when exiting): https://twitter.com/UPK_LS13/status/559817367853989888

**Comment by mor2000** [comment]
should be fixed, but waiting for your testing

**Comment by dajnet** [comment]
yes, this works great!
