### ISSUE TITLE
Pallet Trigger "wool"

### ISSUE THREAD

**Issue by jhomer** [mor2000/UniversalProcessKit_FS15#39]
Done some testing with a couple of "WIP" mods and these triggers do not seem to work well with the actual "pallet spawner" area.

- I have tried the "dissolve" trigger and a "sell" trigger on the "pallet spawner" area
- each of these do make the wool pallet disappear as they should but it doesn't seem to update the spawner ground as the animals sheep menu still shows 2000 or 100% and does not produce any more wool.

**Comment by mor2000** [comment]
the spawner near the sheep farm? you placed a trigger on top?

**Comment by jhomer** [comment]
I tried it first with the trigger on top of the pallet spawner for the sheep.
The last I tried was with an entity trigger that triggered an "animator"

When the person would walk up to the spawner area that would trigger the entity which would then trigger the "animator" and this would then move the "sell" or "dissolve" trigger down to the spawner area.

In all instances the pallet would disappear as it should and also in all instances the animal sheep menu would say 2000 or 100% even after the pallet is gone and will not produce anymore wool because it thinks the pallet is still there.

**Comment by mor2000** [comment]
maybe the spawning pad checks if anything - like a pallet, a tractor or even an other trigger - is on top of it and doesnt spawn a new pallet. maybe you can move the trigger in an out from the side (usually things look down from atop if sth is bellow)

**Comment by jhomer** [comment]
Thanks for the suggestion! I gave that a shot with everything moved away from the pallet spawner area  where the trigger moves from side to side but ended up with the same result. Kind of odd that the pallet disappears but it thinks its still there.

**Comment by dajnet** [comment]
I once tried to put a pallet sell trigger on the spawn area and had lock up problems. A solution that worked for me at that point was to use marhus wool pallet collector to move the pallet from the sell point and into the trigger. It will probably work for this as well.

**Comment by jhomer** [comment]
Thanks @dajnet. I had only tried with the original spawner area. I'll have to go with the marhu pallet collector idea.
