### ISSUE TITLE
 PlayerSpawner

### ISSUE THREAD

**Issue by VAHA022ru** [mor2000/UniversalProcessKit_FS15#49]
hallo mor2000, Ich habe eine Frage, um die damit verbundene   PlayerSpawner
Bitte erläutern Sie, wie er handeln soll, habe ich versucht, Unit-Test, aber das geschieht nicht.
Viele Grüße VAHA022ru

**Comment by mor2000** [comment]
Hey! (English is better, Google does a really bad job translating into German) If you place the example mods UPK_PlayerSpawnerTest somewhere on your map and no vehicle is inside it, you can "jump" from one to the other by hitting "<" on your keyboard (as player outside a vehicle). Its like skipping through vehicles with tab, just with places for a player.

**Comment by VAHA022ru** [comment]
Hi, thanks for your reply now understand why this feature.
Yes indeed Google is not doing very well German translation
