### ISSUE TITLE
sun rain temperature als productionPrerequisite bzw. recipe im Processor unklar 

### ISSUE THREAD

**Issue by thoralf2002** [mor2000/UniversalProcessKit_FS15#55]
Hallo mor2000, ich habe versucht einen solarcolector zum laufen zu bringen, dabei die Angabe productionPrerequisite 1 sun verwendet, leider zeigt sich, dass kein product money zustande kommt. 
Was würde bei dem Type sun eine mengenangabe bewirken, aber auch rain. Bei temperature wird sicher die in Game Temperatur verwendet - oder?
Bitte mal ein Beispiel wie diese Filltypes zu verwenden sind, mit einem für mich verständlichem Beispiel. 
Bzw. ob sun rain temperature überhaupt schon für etwas verwendet werden kann...
Danke

**Comment by mor2000** [comment]
Hab sogar eine Wiki-Seite dafür gemacht: http://wiki.universalprocesskit.de/index.php?title=F%C3%BClltypen
die 3 speziellen Fülltypen müssen noch überarbeitet werden, damit lässt sich noch nichts anfangen

**Comment by thoralf2002** [comment]
Danke für den Hinweis das sie momentan nur aufgeführt sind ;)
