### ISSUE TITLE
Werte der Collision Mask

### ISSUE THREAD

**Issue by Dimer24** [mor2000/UniversalProcessKit_FS15#56]
Ich habe in einige Triggertestdateien die "Collison Mask" verglichen.

Ich frag mich nun was für eine Auswirkung hat die "Collision Mask" wenn sie in diveren Triggern andere Werte hat.
Ist dieser Wert unwichtig? Reicht die Einträge  allowWalker allowShovel allowTipper und er Wert im Trigger muss nicht beachtet werden.

NAME....................................displaytrigger........emptytrigger.....filltrigger......Dumptrigger
UPK_DisplayTriggerTest.......f00000
UPK_DumpTriggerTest.........0........................................................................800000
UPK_MilkTest........................0..........................0.......................0
UPK_ProcessorTest..............f00000
UPK_ProcessorTest2............500000
UPK_ProcessorTest3............0

Freundliche Grüsse

Dimer24

**Comment by mor2000** [comment]
die collisionMask wird jeweils vom UPK angepasst, was unter allowXY angegeben wurde. Prinzipiell muss man darauf also nicht achten. Im Debug-Modus erscheinen "Warnungen" mit der Angabe, welche collisionMask gesetzt sein müsste, wenn man sie manuell richtig setzen möchte.

**Comment by Dimer24** [comment]
Hi mor200

Danke für die Infos.

Wie kann ich den Debug-Modus einschalten?

Gruss Dimer24

**Comment by Dimer24** [comment]
Hallo zusammen

Der Debug-Modus kann in der Debug.lua eingeschalten werden.

1. AAA_UniversalProcessKit.zip entpacken
2. DEBUG.lua öffnen
3. debugMode=false -- DEBUG (print a lot of messages to log)
    false in true ändern
    debugMode=true -- DEBUG (print a lot of messages to log)
4. AAA_UniversalProcessKit.zip neu erstellen
5. Spiel starten danach sind in der LOG Datei
    ..\Dokumente\My Games\FarmingSimulator2015\log.txt
    viele Debug-Einträge

Viel Spass ;-)

Dimer 24
