### ISSUE TITLE
UPK_ActivatorTriggerTest2 Not Working With V0.9.10

### ISSUE THREAD

**Issue by bigdaddy012678** [mor2000/UniversalProcessKit_FS15#59]
Hello,
I am testing the new Universal Process Kit V0.9.10 and the UPK_ActivatorTriggerTest 2 and cannot buy pigs. I place it on the Bjornholm map, it gives me the options to buy pigs with the "R" button, but nothing happens. Maybe I am not doing it correctly, please advise.

![upk_activatortriggertest2notworking](https://cloud.githubusercontent.com/assets/12091807/7594926/e00ecc04-f8b1-11e4-8c9e-ea305c3750ba.jpg)

Bigdaddy

**Comment by mor2000** [comment]
Thanks, I'll check that.
