### ISSUE TITLE
Mixing things up .

### ISSUE THREAD

**Issue by litlebuda** [mor2000/UniversalProcessKit_FS15#64]
Hi .

Is it possible to : 
- Combine upk trigers to non upk mods  ( add upk filltriger to Slurry storage )?
-Add a isSilo bolean to an upk mod. ( Make a upk slurry storage be recognized in game as a Silo  and showing in satistics ?
If sameone coul point me to some documentation on this i would apreciate it . I've read the documentation pdf , but it did not explain this .

Thanks

**Comment by mor2000** [comment]
Hi,
1) combining upk triggers with others is not possible
2) statistics cannot be shown on the stats page yet
3) theres a wiki: wiki.universalprocesskit.de
:)

**Comment by litlebuda** [comment]
Thank's for the quick response and a great job with upk .
