### ISSUE TITLE
Probleme mit activateText deactivateText bei Maps

### ISSUE THREAD

**Issue by thoralf2002** [mor2000/UniversalProcessKit_FS15#66]
Hi Fabian, mir ist aufgefallen das die Einträge dazu nur sporadisch erkannt werden - meistens betrifft es fest verbaute Module in den Maps, manchmal leider leider auch Mods, wo diese Angaben nicht erfasst werden. Betrifft die stable Version 0.9.8
Gruß Peter

**Comment by mngrazy** [comment]
fixed in 0.10.3

**Comment by thoralf2002** [comment]
Thanks for this reply :-)
