### ISSUE TITLE
Keine Preisanzeige bei PelletTrigger

### ISSUE THREAD

**Issue by Farmer-Steven** [mor2000/UniversalProcessKit_FS15#68]
Hallo mor2000, mit dem UPK hast du was richtig tolles entwickelt, da kann man nur den Hut vor ziehen.
Im Moment arbeite ich mich in's UPK ein, beim PelletTrigger bin ich jetzt auf ein Problem oder Feature gestoßen. Es geht um die Preisanzeige beim Verkauf von Wolle, es wird weder der Verkaufsort (stationName) noch ein Preis angezeigt. Ist das ein normales Verhalten, wenn ja, kann ich das mit dem Woll-Verkauf anders lösen (mit dem UPK), dass ein Preis angezeigt wird.

Vielen Dank schon mal im Voraus.
Gruß vom Farmer
Steven

**Comment by mor2000** [comment]
hi Steven,

der Preis wird nirgends angezeigt, da hast du Recht. die Tabelle mit den Verkaufsstellen und den Fruchtsorten finde ich Käse, weil die allermeisten Zellen leer sind. da möcht ich mich nicht ranhängen. das müsste mal jemand modden dass das Sinn macht ;)

du kannst einen displaytrigger misbrauchen, der nur den Preis anzeigt. füllstand ist dann 1.23 dummyXY oder irgendwas, mit 2 kommastellen anzeigen und in der moddesc im l10n abschnitt dummyXY_unit_short und dummyXY_unit_long auf "€" setzen (modname in der base nicht vergessen).

vg
